/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MemosPlugin
});
module.exports = __toCommonJS(main_exports);

// src/plugin.ts
var import_obsidian7 = require("obsidian");

// src/constants.ts
var VIEW_TYPE_MEMOS = "memos-view";
var VIEW_TYPE_CAPTURE = "memos-capture-view";
var INLINE_TAG_RE = /#([\w\u4e00-\u9fff\u3040-\u309f\u30a0-\u30ff\uac00-\ud7af/-]+)/g;
var WIKILINK_RE = /\[\[([^\]|]+?)(?:\|([^\]]+?))?\]\]/g;

// src/types.ts
var DEFAULT_SETTINGS = {
  saveFolder: "00-Inbox",
  useFixedTag: false,
  fixedTag: "",
  captureNotePath: "Quick Capture.md",
  statsCollapsed: false,
  authorName: "",
  showAuthorInExport: false,
  showBrandingInExport: true,
  enableMood: false,
  enableSource: false,
  moodOptions: ["\u{1F4A1}", "\u{1F914}", "\u{1F60A}", "\u{1F624}", "\u{1F4D6}"],
  sourceOptions: ["thought", "kindle", "web", "conversation", "podcast"]
};

// src/view.ts
var import_obsidian4 = require("obsidian");

// src/utils.ts
function extractInlineTags(text) {
  const tags = [];
  let m;
  const re = new RegExp(INLINE_TAG_RE.source, INLINE_TAG_RE.flags);
  while ((m = re.exec(text)) !== null) {
    tags.push(m[1]);
  }
  return tags;
}
function parseTags(input) {
  return input.split(/[\s,，]+/).map((t) => t.replace(/^#+/, "").trim()).filter((t) => t.length > 0);
}

// src/memo-parser.ts
function parseMemoContent(raw, fm, frontmatterEndOffset) {
  let body = raw;
  if (frontmatterEndOffset != null) {
    body = raw.slice(frontmatterEndOffset).trimStart();
  } else if (raw.startsWith("---")) {
    const end = raw.indexOf("---", 3);
    if (end !== -1) {
      body = raw.slice(end + 3).trimStart();
    }
  }
  const inlineTags = extractInlineTags(body);
  const fmTags = [];
  if (Array.isArray(fm["tags"])) {
    for (const t of fm["tags"]) {
      if (typeof t === "string")
        fmTags.push(t);
    }
  }
  const tags = Array.from(/* @__PURE__ */ new Set([...fmTags, ...inlineTags]));
  return { body, tags };
}

// src/stats.ts
var import_obsidian = require("obsidian");
function computeStats(memos) {
  var _a, _b;
  const dailyCounts = /* @__PURE__ */ new Map();
  for (const memo of memos) {
    dailyCounts.set(memo.dateLabel, ((_a = dailyCounts.get(memo.dateLabel)) != null ? _a : 0) + 1);
  }
  const now = /* @__PURE__ */ new Date();
  const pad = (n) => n.toString().padStart(2, "0");
  const todayLabel = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`;
  const monthPrefix = todayLabel.slice(0, 7);
  const total = memos.length;
  const today = (_b = dailyCounts.get(todayLabel)) != null ? _b : 0;
  let thisMonth = 0;
  for (const [label, count] of dailyCounts) {
    if (label.startsWith(monthPrefix)) {
      thisMonth += count;
    }
  }
  const streak = computeStreak(dailyCounts, todayLabel);
  return { total, streak, today, thisMonth, dailyCounts };
}
function computeStreak(dailyCounts, todayLabel) {
  const todayDate = /* @__PURE__ */ new Date(todayLabel + "T00:00:00");
  let startOffset = dailyCounts.has(todayLabel) ? 0 : 1;
  let streak = 0;
  for (let i = startOffset; ; i++) {
    const d = new Date(todayDate);
    d.setDate(d.getDate() - i);
    const label = `${d.getFullYear()}-${(d.getMonth() + 1).toString().padStart(2, "0")}-${d.getDate().toString().padStart(2, "0")}`;
    if (dailyCounts.has(label)) {
      streak++;
    } else {
      break;
    }
  }
  return streak;
}
function getLevel(count) {
  if (count === 0)
    return 0;
  if (count === 1)
    return 1;
  if (count <= 3)
    return 2;
  if (count <= 6)
    return 3;
  return 4;
}
function renderHeatmap(container, dailyCounts, onDateClick) {
  var _a;
  const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  const WEEKDAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
  const wrap = container.createDiv("memos-heatmap-wrap");
  const weekdayLabels = wrap.createDiv("memos-heatmap-weekday-labels");
  weekdayLabels.createDiv("memos-heatmap-weekday-spacer");
  for (let dow = 0; dow < 7; dow++) {
    const lbl = weekdayLabels.createDiv("memos-heatmap-weekday-label");
    if (dow === 0 || dow === 2 || dow === 4) {
      lbl.textContent = WEEKDAYS[dow];
    }
  }
  const gridArea = wrap.createDiv("memos-heatmap-grid-area");
  const today = /* @__PURE__ */ new Date();
  today.setHours(0, 0, 0, 0);
  const dayOfWeek = today.getDay();
  const mondayOffset = dayOfWeek === 0 ? 6 : dayOfWeek - 1;
  const thisMonday = new Date(today);
  thisMonday.setDate(today.getDate() - mondayOffset);
  const startDate = new Date(thisMonday);
  startDate.setDate(startDate.getDate() - 16 * 7);
  const pad = (n) => n.toString().padStart(2, "0");
  const monthRow = gridArea.createDiv("memos-heatmap-month-labels");
  let prevMonth = -1;
  for (let week = 0; week < 17; week++) {
    const d = new Date(startDate);
    d.setDate(d.getDate() + week * 7);
    const month = d.getMonth();
    const monthLabel = monthRow.createDiv("memos-heatmap-month-label");
    if (month !== prevMonth) {
      monthLabel.textContent = MONTHS[month];
      prevMonth = month;
    }
  }
  const heatmap = gridArea.createDiv("memos-heatmap");
  for (let week = 0; week < 17; week++) {
    for (let dow = 0; dow < 7; dow++) {
      const d = new Date(startDate);
      d.setDate(d.getDate() + week * 7 + dow);
      const label = `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
      const count = (_a = dailyCounts.get(label)) != null ? _a : 0;
      const level = getLevel(count);
      if (d > today) {
        heatmap.createDiv("memos-heatmap-cell memos-heatmap-empty");
        continue;
      }
      const cell = heatmap.createDiv({
        cls: `memos-heatmap-cell memos-heatmap-level-${level}`,
        attr: {
          "data-tooltip": `${label}: ${count} memo${count !== 1 ? "s" : ""}`,
          "data-date": label
        }
      });
      if (count > 0) {
        cell.addEventListener("click", () => {
          onDateClick(label);
        });
      }
    }
  }
}
function renderStatsSection(container, stats, collapsed, callbacks) {
  const section = container.createDiv("memos-stats-section");
  const header = section.createDiv("memos-stats-header");
  const chevron = header.createSpan("memos-stats-chevron");
  (0, import_obsidian.setIcon)(chevron, collapsed ? "chevron-right" : "chevron-down");
  header.createSpan({ cls: "memos-stats-title", text: "Stats" });
  header.addEventListener("click", () => {
    callbacks.onToggle();
  });
  const content = section.createDiv({
    cls: `memos-stats-content${collapsed ? " memos-stats-collapsed" : ""}`
  });
  if (!collapsed) {
    renderHeatmap(content, stats.dailyCounts, callbacks.onDateClick);
    const numbers = content.createDiv("memos-stats-numbers");
    renderStatCard(numbers, "\u603B\u8BA1", String(stats.total));
    renderStatCard(numbers, "\u8FDE\u7EED", String(stats.streak), "\u5929");
    renderStatCard(numbers, "\u4ECA\u65E5", String(stats.today));
    renderStatCard(numbers, "\u672C\u6708", String(stats.thisMonth));
  }
}
function renderStatCard(container, label, value, unit) {
  const card = container.createDiv("memos-stat-card");
  const valueEl = card.createDiv("memos-stat-value");
  valueEl.createSpan({ text: value });
  if (unit) {
    valueEl.createSpan({ cls: "memos-stat-unit", text: ` ${unit}` });
  }
  card.createDiv({ cls: "memos-stat-label", text: label });
}

// src/export-image.ts
var import_obsidian2 = require("obsidian");
var LIGHT_THEME = {
  bgGradientStart: "#ffffff",
  bgGradientEnd: "#f8f9fa",
  textColor: "#1a1a1a",
  tagColor: "#6b7280",
  metaBorderColor: "rgba(0, 0, 0, 0.06)",
  timeColor: "#9ca3af",
  authorColor: "#9ca3af",
  brandingColor: "#c9cdd4"
};
var DARK_THEME = {
  bgGradientStart: "#1e1e1e",
  bgGradientEnd: "#2a2a2a",
  textColor: "#e0e0e0",
  tagColor: "#9ca3af",
  metaBorderColor: "rgba(255, 255, 255, 0.08)",
  timeColor: "#6b7280",
  authorColor: "#6b7280",
  brandingColor: "#4a4a4a"
};
var CARD_WIDTH = 440;
var PADDING_X = 28;
var PADDING_TOP = 32;
var PADDING_BOTTOM = 24;
var BORDER_RADIUS = 16;
var CONTENT_FONT_SIZE = 16;
var CONTENT_LINE_HEIGHT = 1.8;
var META_FONT_SIZE = 12;
var BRANDING_FONT_SIZE = 10;
var BRANDING_TEXT = "Quick Memos for Obsidian";
var FONT_FAMILY = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif";
var PIXEL_RATIO = 2;
function parseContentSegments(content) {
  const lines = content.split("\n");
  const result = [];
  const re = new RegExp(INLINE_TAG_RE.source, INLINE_TAG_RE.flags);
  for (const line of lines) {
    const segments = [];
    let lastIndex = 0;
    let match;
    re.lastIndex = 0;
    while ((match = re.exec(line)) !== null) {
      if (match.index > lastIndex) {
        segments.push({ text: line.slice(lastIndex, match.index), isTag: false });
      }
      segments.push({ text: `#${match[1]}`, isTag: true });
      lastIndex = re.lastIndex;
    }
    if (lastIndex < line.length) {
      segments.push({ text: line.slice(lastIndex), isTag: false });
    }
    if (segments.length === 0) {
      segments.push({ text: "", isTag: false });
    }
    result.push(segments);
  }
  return result;
}
function wrapSegmentLines(ctx, segments, maxWidth, fontSize) {
  const visualLines = [];
  for (const lineSegments of segments) {
    let currentLine = [];
    let lineX = 0;
    for (const seg of lineSegments) {
      ctx.font = seg.isTag ? `500 ${fontSize}px ${FONT_FAMILY}` : `normal ${fontSize}px ${FONT_FAMILY}`;
      const chars = Array.from(seg.text);
      let buf = "";
      for (const ch of chars) {
        const testWidth = ctx.measureText(buf + ch).width;
        if (lineX + testWidth > maxWidth && (buf.length > 0 || currentLine.length > 0)) {
          if (buf.length > 0) {
            currentLine.push({ text: buf, isTag: seg.isTag, x: lineX });
            lineX += ctx.measureText(buf).width;
          }
          visualLines.push(currentLine);
          currentLine = [];
          lineX = 0;
          buf = ch;
        } else {
          buf += ch;
        }
      }
      if (buf.length > 0) {
        currentLine.push({ text: buf, isTag: seg.isTag, x: lineX });
        lineX += ctx.measureText(buf).width;
      }
    }
    visualLines.push(currentLine);
  }
  return visualLines;
}
async function generateImage(memo, options) {
  const theme = options.isDarkMode ? DARK_THEME : LIGHT_THEME;
  const scale = PIXEL_RATIO;
  const maxTextWidth = CARD_WIDTH - PADDING_X * 2;
  const lineHeight = CONTENT_FONT_SIZE * CONTENT_LINE_HEIGHT;
  const measureCanvas = document.createElement("canvas");
  measureCanvas.width = CARD_WIDTH * scale;
  measureCanvas.height = 1;
  const mCtx = measureCanvas.getContext("2d");
  mCtx.scale(scale, scale);
  mCtx.font = `normal ${CONTENT_FONT_SIZE}px ${FONT_FAMILY}`;
  const segmentLines = parseContentSegments(memo.content);
  const wrappedLines = wrapSegmentLines(mCtx, segmentLines, maxTextWidth, CONTENT_FONT_SIZE);
  const contentHeight = wrappedLines.length * lineHeight;
  const metaGap = 20;
  const dividerHeight = 1;
  const metaPaddingTop = 14;
  const footerHeight = META_FONT_SIZE * 1.5;
  const brandingOnSeparateLine = options.showBranding && !!options.authorName;
  const brandingHeight = brandingOnSeparateLine ? BRANDING_FONT_SIZE + 16 : 0;
  const totalHeight = PADDING_TOP + contentHeight + metaGap + dividerHeight + metaPaddingTop + footerHeight + brandingHeight + PADDING_BOTTOM;
  const canvas = document.createElement("canvas");
  canvas.width = CARD_WIDTH * scale;
  canvas.height = totalHeight * scale;
  const ctx = canvas.getContext("2d");
  ctx.scale(scale, scale);
  const grad = ctx.createLinearGradient(0, 0, CARD_WIDTH * 0.6, totalHeight * 0.6);
  grad.addColorStop(0, theme.bgGradientStart);
  grad.addColorStop(1, theme.bgGradientEnd);
  ctx.fillStyle = grad;
  roundRect(ctx, 0, 0, CARD_WIDTH, totalHeight, BORDER_RADIUS);
  ctx.fill();
  let y = PADDING_TOP + CONTENT_FONT_SIZE;
  for (const vLine of wrappedLines) {
    for (const seg of vLine) {
      if (seg.isTag) {
        ctx.font = `500 ${CONTENT_FONT_SIZE}px ${FONT_FAMILY}`;
        ctx.fillStyle = theme.tagColor;
      } else {
        ctx.font = `normal ${CONTENT_FONT_SIZE}px ${FONT_FAMILY}`;
        ctx.fillStyle = theme.textColor;
      }
      ctx.fillText(seg.text, PADDING_X + seg.x, y);
    }
    y += lineHeight;
  }
  const dividerY = PADDING_TOP + contentHeight + metaGap;
  ctx.fillStyle = theme.metaBorderColor;
  ctx.fillRect(PADDING_X, dividerY, maxTextWidth, dividerHeight);
  const footerY = dividerY + dividerHeight + metaPaddingTop + META_FONT_SIZE;
  const d = new Date(memo.created);
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  const hh = String(d.getHours()).padStart(2, "0");
  const min = String(d.getMinutes()).padStart(2, "0");
  const timeText = `${yyyy}-${mm}-${dd} ${hh}:${min}`;
  ctx.font = `300 ${META_FONT_SIZE}px ${FONT_FAMILY}`;
  ctx.fillStyle = theme.timeColor;
  ctx.fillText(timeText, PADDING_X, footerY);
  if (options.authorName) {
    const authorText = `\u2014 ${options.authorName}`;
    ctx.font = `italic 400 ${META_FONT_SIZE}px ${FONT_FAMILY}`;
    ctx.fillStyle = theme.authorColor;
    const authorWidth = ctx.measureText(authorText).width;
    ctx.fillText(authorText, CARD_WIDTH - PADDING_X - authorWidth, footerY);
  }
  if (options.showBranding) {
    ctx.font = `300 ${BRANDING_FONT_SIZE}px ${FONT_FAMILY}`;
    ctx.fillStyle = theme.brandingColor;
    const brandingWidth = ctx.measureText(BRANDING_TEXT).width;
    if (options.authorName) {
      const brandingY = footerY + BRANDING_FONT_SIZE + 16;
      ctx.fillText(BRANDING_TEXT, CARD_WIDTH - PADDING_X - brandingWidth, brandingY);
    } else {
      ctx.fillText(BRANDING_TEXT, CARD_WIDTH - PADDING_X - brandingWidth, footerY);
    }
  }
  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (blob) => {
        if (blob)
          resolve(blob);
        else
          reject(new Error("Canvas toBlob returned null"));
      },
      "image/png"
    );
  });
}
function roundRect(ctx, x, y, w, h, r) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}
function renderExportContent(content, container) {
  const lines = content.split("\n");
  const re = new RegExp(INLINE_TAG_RE.source, INLINE_TAG_RE.flags);
  for (let i = 0; i < lines.length; i++) {
    if (i > 0)
      container.appendChild(document.createElement("br"));
    const line = lines[i];
    let lastIndex = 0;
    let match;
    re.lastIndex = 0;
    while ((match = re.exec(line)) !== null) {
      if (match.index > lastIndex) {
        container.appendChild(
          document.createTextNode(line.slice(lastIndex, match.index))
        );
      }
      const tagSpan = document.createElement("span");
      tagSpan.className = "memos-export-inline-tag";
      tagSpan.textContent = `#${match[1]}`;
      container.appendChild(tagSpan);
      lastIndex = re.lastIndex;
    }
    if (lastIndex < line.length) {
      container.appendChild(
        document.createTextNode(line.slice(lastIndex))
      );
    }
  }
}
function buildExportCard(memo, options) {
  const card = document.createElement("div");
  card.className = "memos-export-card";
  if (options.isDarkMode)
    card.classList.add("memos-export-dark");
  const contentDiv = document.createElement("div");
  contentDiv.className = "memos-export-content";
  renderExportContent(memo.content, contentDiv);
  card.appendChild(contentDiv);
  const meta = document.createElement("div");
  meta.className = "memos-export-meta";
  const footer = document.createElement("div");
  footer.className = "memos-export-footer";
  const d = new Date(memo.created);
  const timeSpan = document.createElement("span");
  timeSpan.className = "memos-export-time";
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  const hh = String(d.getHours()).padStart(2, "0");
  const min = String(d.getMinutes()).padStart(2, "0");
  timeSpan.textContent = `${yyyy}-${mm}-${dd} ${hh}:${min}`;
  footer.appendChild(timeSpan);
  if (options.authorName) {
    const authorSpan = document.createElement("span");
    authorSpan.className = "memos-export-author";
    authorSpan.textContent = `\u2014 ${options.authorName}`;
    footer.appendChild(authorSpan);
  }
  meta.appendChild(footer);
  if (options.showBranding) {
    if (options.authorName) {
      const branding = document.createElement("div");
      branding.className = "memos-export-branding";
      branding.textContent = BRANDING_TEXT;
      meta.appendChild(branding);
    } else {
      const branding = document.createElement("span");
      branding.className = "memos-export-branding";
      branding.textContent = BRANDING_TEXT;
      footer.appendChild(branding);
    }
  }
  card.appendChild(meta);
  return card;
}
var ExportModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, memo) {
    super(app);
    this.plugin = plugin;
    this.memo = memo;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.addClass("memos-export-modal");
    const isDarkMode = document.body.classList.contains("theme-dark");
    const authorName = this.plugin.settings.showAuthorInExport ? this.plugin.settings.authorName : void 0;
    const showBranding = this.plugin.settings.showBrandingInExport;
    const cardEl = buildExportCard(this.memo, { authorName, isDarkMode, showBranding });
    const previewContainer = contentEl.createDiv("memos-export-preview");
    const cardWrapper = previewContainer.createDiv("memos-export-card-wrapper");
    cardWrapper.appendChild(cardEl);
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        const containerWidth = previewContainer.clientWidth - 40;
        const cardWidth = 440;
        if (containerWidth < cardWidth) {
          const scale = containerWidth / cardWidth;
          cardEl.style.transform = `scale(${scale})`;
          cardEl.style.transformOrigin = "top left";
          const cardHeight = cardEl.offsetHeight;
          cardWrapper.style.width = `${cardWidth * scale}px`;
          cardWrapper.style.height = `${cardHeight * scale}px`;
          cardWrapper.style.overflow = "hidden";
        }
      });
    });
    const btnRow = contentEl.createDiv("memos-export-btn-row");
    const saveBtn = btnRow.createEl("button", {
      cls: "memos-export-btn mod-cta",
      text: "Save as PNG"
    });
    saveBtn.addEventListener("click", () => this.handleSave(isDarkMode));
    const copyBtn = btnRow.createEl("button", {
      cls: "memos-export-btn",
      text: "Copy to clipboard"
    });
    copyBtn.addEventListener("click", () => this.handleCopy(isDarkMode));
  }
  /** Build filename from memo date. */
  buildFilename() {
    const d = new Date(this.memo.created);
    return `memo-${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, "0")}${String(d.getDate()).padStart(2, "0")}-${String(d.getHours()).padStart(2, "0")}${String(d.getMinutes()).padStart(2, "0")}.png`;
  }
  /** Get export options for Canvas image generation. */
  getExportOptions(isDarkMode) {
    const authorName = this.plugin.settings.showAuthorInExport ? this.plugin.settings.authorName : void 0;
    const showBranding = this.plugin.settings.showBrandingInExport;
    return { authorName, isDarkMode, showBranding };
  }
  async handleSave(isDarkMode) {
    try {
      const blob = await generateImage(this.memo, this.getExportOptions(isDarkMode));
      const fname = this.buildFilename();
      if (import_obsidian2.Platform.isMobile) {
        await this.handleMobileSave(blob, fname);
      } else {
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = fname;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        new import_obsidian2.Notice("Image saved!");
      }
      this.close();
    } catch (err) {
      new import_obsidian2.Notice(
        `Export failed: ${err instanceof Error ? err.message : String(err)}`
      );
    }
  }
  /** Mobile save: try Web Share API first, fall back to saving into the vault. */
  async handleMobileSave(blob, fname) {
    const file = new File([blob], fname, { type: "image/png" });
    if (navigator.share && navigator.canShare && navigator.canShare({ files: [file] })) {
      try {
        await navigator.share({ files: [file] });
        return;
      } catch (shareErr) {
        if (shareErr instanceof Error && shareErr.name === "AbortError")
          return;
      }
    }
    const saveFolder = this.plugin.settings.saveFolder;
    const vaultPath = `${saveFolder}/${fname}`;
    const arrayBuf = await blob.arrayBuffer();
    await this.app.vault.createBinary(vaultPath, arrayBuf);
    new import_obsidian2.Notice(`Image saved to ${vaultPath}`);
  }
  async handleCopy(isDarkMode) {
    try {
      const blob = await generateImage(this.memo, this.getExportOptions(isDarkMode));
      await navigator.clipboard.write([
        new ClipboardItem({ "image/png": blob })
      ]);
      new import_obsidian2.Notice("Image copied to clipboard!");
      this.close();
    } catch (err) {
      new import_obsidian2.Notice(
        `Copy failed: ${err instanceof Error ? err.message : String(err)}`
      );
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/canvas-export.ts
var import_obsidian3 = require("obsidian");
var CARD_W = 260;
var CARD_H = 160;
var GAP_Y = 20;
var GROUP_GAP_X = 80;
async function exportToCanvas(app, memos, canvasName) {
  var _a;
  if (memos.length === 0) {
    new import_obsidian3.Notice("No memos to export.");
    return;
  }
  const groups = /* @__PURE__ */ new Map();
  for (const memo of memos) {
    const groupKey = memo.tags.length > 0 ? memo.tags[0] : "untagged";
    const list = (_a = groups.get(groupKey)) != null ? _a : [];
    list.push(memo);
    groups.set(groupKey, list);
  }
  const nodes = [];
  let groupX = 0;
  for (const [, groupMemos] of groups) {
    for (let i = 0; i < groupMemos.length; i++) {
      const memo = groupMemos[i];
      nodes.push({
        id: memo.file.basename,
        type: "file",
        file: memo.file.path,
        x: groupX,
        y: i * (CARD_H + GAP_Y),
        width: CARD_W,
        height: CARD_H
      });
    }
    groupX += CARD_W + GROUP_GAP_X;
  }
  const canvasData = { nodes, edges: [] };
  const filename = canvasName || `Memo Board ${(/* @__PURE__ */ new Date()).toISOString().slice(0, 10)}.canvas`;
  const path = (0, import_obsidian3.normalizePath)(filename);
  const content = JSON.stringify(canvasData, null, 2);
  const existing = app.vault.getAbstractFileByPath(path);
  if (existing && existing instanceof import_obsidian3.TFile) {
    await app.vault.modify(existing, content);
  } else {
    await app.vault.create(path, content);
  }
  const canvasFile = app.vault.getAbstractFileByPath(path);
  if (canvasFile && canvasFile instanceof import_obsidian3.TFile) {
    const leaf = app.workspace.getLeaf("tab");
    await leaf.openFile(canvasFile);
  }
  new import_obsidian3.Notice(`Exported ${memos.length} memos to Canvas!`);
}

// src/view.ts
var _MemosView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.activeTag = null;
    this.activeDateFilter = null;
    this.memos = [];
    this.highlightedCardEl = null;
    this.refreshTimer = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_MEMOS;
  }
  getDisplayText() {
    return "Memos";
  }
  getIcon() {
    return "sticky-note";
  }
  /** Debounced refresh — coalesces rapid vault events into a single refresh. */
  debouncedRefresh() {
    if (this.refreshTimer)
      clearTimeout(this.refreshTimer);
    this.refreshTimer = setTimeout(() => {
      this.refreshTimer = null;
      this.refresh();
    }, 300);
  }
  async onOpen() {
    this.contentEl.addClass("memos-view");
    await this.refresh();
    const folderPrefix = (0, import_obsidian4.normalizePath)(this.plugin.settings.saveFolder) + "/";
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (file instanceof import_obsidian4.TFile && file.path.startsWith(folderPrefix))
          this.debouncedRefresh();
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian4.TFile && file.path.startsWith(folderPrefix))
          this.debouncedRefresh();
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian4.TFile && file.path.startsWith(folderPrefix))
          this.debouncedRefresh();
      })
    );
  }
  async onClose() {
    if (this.refreshTimer) {
      clearTimeout(this.refreshTimer);
      this.refreshTimer = null;
    }
  }
  async refresh() {
    await this.loadMemos();
    this.contentEl.empty();
    this.highlightedCardEl = null;
    const toolbar = this.contentEl.createDiv("memos-toolbar");
    this.renderToolbar(toolbar);
    const statsContainer = this.contentEl.createDiv();
    const stats = computeStats(this.memos);
    renderStatsSection(statsContainer, stats, this.plugin.settings.statsCollapsed, {
      onToggle: () => this.handleStatsToggle(),
      onDateClick: (date) => this.handleDateFilter(date)
    });
    const cardsContainer = this.contentEl.createDiv("memos-cards-container");
    this.renderCards(cardsContainer);
  }
  async loadMemos() {
    const folder = (0, import_obsidian4.normalizePath)(this.plugin.settings.saveFolder);
    const abstractFolder = this.app.vault.getAbstractFileByPath(folder);
    if (!abstractFolder || !(abstractFolder instanceof import_obsidian4.TFolder)) {
      this.memos = [];
      return;
    }
    const files = abstractFolder.children.filter(
      (f) => f instanceof import_obsidian4.TFile && f.name.endsWith(".md")
    );
    const results = [];
    for (const file of files) {
      const cache = this.app.metadataCache.getFileCache(file);
      const fm = cache == null ? void 0 : cache.frontmatter;
      if (!fm || fm["type"] !== "memo")
        continue;
      const raw = await this.app.vault.read(file);
      const memo = this.parseMemo(file, raw, fm, cache);
      results.push(memo);
    }
    results.sort((a, b) => b.created.localeCompare(a.created));
    this.memos = results;
  }
  parseMemo(file, raw, fm, cache) {
    var _a, _b;
    const fmEndOffset = (_b = (_a = cache == null ? void 0 : cache.frontmatterPosition) == null ? void 0 : _a.end) == null ? void 0 : _b.offset;
    const { body, tags } = parseMemoContent(raw, fm, fmEndOffset);
    const created = typeof fm["created"] === "string" ? fm["created"] : file.stat.ctime ? new Date(file.stat.ctime).toISOString() : (/* @__PURE__ */ new Date()).toISOString();
    const dateLabel = created.slice(0, 10);
    const mood = typeof fm["mood"] === "string" ? fm["mood"].replace(/^"|"$/g, "") : "";
    const source = typeof fm["source"] === "string" ? fm["source"].replace(/^"|"$/g, "") : "";
    return { file, content: body, tags, created, dateLabel, mood, source };
  }
  renderToolbar(el) {
    const left = el.createDiv("memos-toolbar-left");
    const count = this.memos.filter(
      (m) => (!this.activeTag || m.tags.includes(this.activeTag)) && (!this.activeDateFilter || m.dateLabel === this.activeDateFilter)
    ).length;
    left.createSpan({
      cls: "memos-count",
      text: `${count} memo${count !== 1 ? "s" : ""}`
    });
    if (this.activeTag) {
      const pill = left.createSpan({ cls: "memos-active-filter-pill" });
      pill.setText(`#${this.activeTag}`);
      const x = pill.createSpan({ cls: "memos-filter-clear", text: " \xD7" });
      x.addEventListener("click", () => {
        this.activeTag = null;
        this.refresh();
      });
    }
    if (this.activeDateFilter) {
      const pill = left.createSpan({ cls: "memos-active-filter-pill memos-date-filter-pill" });
      pill.setText(this.activeDateFilter);
      const x = pill.createSpan({ cls: "memos-filter-clear", text: " \xD7" });
      x.addEventListener("click", () => {
        this.activeDateFilter = null;
        this.refresh();
      });
    }
    const right = el.createDiv("memos-toolbar-right");
    const captureBtn = right.createDiv({
      cls: "memos-toolbar-btn",
      attr: { "aria-label": "New memo" }
    });
    (0, import_obsidian4.setIcon)(captureBtn, "pencil");
    captureBtn.addEventListener("click", () => {
      this.plugin.activateCaptureView();
    });
    const randomBtn = right.createDiv({
      cls: "memos-toolbar-btn",
      attr: { "aria-label": "Random review" }
    });
    (0, import_obsidian4.setIcon)(randomBtn, "dice");
    randomBtn.addEventListener("click", () => {
      this.handleRandomReview();
    });
    const canvasBtn = right.createDiv({
      cls: "memos-toolbar-btn",
      attr: { "aria-label": "Send to Canvas" }
    });
    (0, import_obsidian4.setIcon)(canvasBtn, "layout-dashboard");
    canvasBtn.addEventListener("click", () => {
      const filtered = this.getFilteredMemos();
      exportToCanvas(this.app, filtered);
    });
  }
  renderCards(el) {
    var _a;
    const filtered = this.getFilteredMemos();
    if (filtered.length === 0) {
      const empty = el.createDiv("memos-empty");
      empty.createSpan({ text: "No memos yet. Start capturing your thoughts!" });
      return;
    }
    const groups = /* @__PURE__ */ new Map();
    for (const memo of filtered) {
      const g = (_a = groups.get(memo.dateLabel)) != null ? _a : [];
      g.push(memo);
      groups.set(memo.dateLabel, g);
    }
    for (const [date, memos] of groups) {
      const group = el.createDiv("memos-date-group");
      group.createDiv({ cls: "memos-date-header", text: date });
      for (const memo of memos) {
        this.renderCard(memo, group);
      }
    }
  }
  renderCard(memo, el) {
    const card = el.createDiv("memos-card");
    card.dataset["path"] = memo.file.path;
    const contentDiv = card.createDiv("memos-card-content");
    this.renderContentDOM(memo.content, contentDiv);
    const footer = card.createDiv("memos-card-footer");
    if (memo.tags.length > 0) {
      const tagsEl = footer.createDiv("memos-card-tags");
      for (const tag of memo.tags) {
        const pill = tagsEl.createSpan({ cls: "memos-tag-pill", text: `#${tag}` });
        pill.addEventListener("click", (e) => {
          e.stopPropagation();
          this.handleTagClick(tag);
        });
      }
    }
    const footerRight = footer.createDiv("memos-card-footer-right");
    if (memo.mood) {
      footerRight.createSpan({ cls: "memos-card-mood", text: memo.mood });
    }
    if (memo.source) {
      footerRight.createSpan({ cls: "memos-card-source", text: memo.source });
    }
    const time = footerRight.createSpan({ cls: "memos-card-time" });
    const d = new Date(memo.created);
    time.setText(
      `${d.getHours().toString().padStart(2, "0")}:${d.getMinutes().toString().padStart(2, "0")}`
    );
    const shareBtn = footerRight.createDiv({
      cls: "memos-card-share-btn",
      attr: { "aria-label": "Export as image" }
    });
    (0, import_obsidian4.setIcon)(shareBtn, "share");
    shareBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      new ExportModal(this.app, this.plugin, memo).open();
    });
    card.addEventListener("click", () => {
      this.openMemo(memo.file);
    });
  }
  /** Build card content using safe DOM operations instead of innerHTML. */
  renderContentDOM(content, container) {
    const lines = content.split("\n");
    for (let i = 0; i < lines.length; i++) {
      if (i > 0)
        container.createEl("br");
      const line = lines[i];
      const embedRe = new RegExp(_MemosView.EMBED_RE.source, _MemosView.EMBED_RE.flags);
      let lastIdx = 0;
      let embedMatch;
      while ((embedMatch = embedRe.exec(line)) !== null) {
        if (embedMatch.index > lastIdx) {
          this.renderTextSegment(line.slice(lastIdx, embedMatch.index), container);
        }
        const embedName = embedMatch[1];
        this.renderEmbed(embedName, container);
        lastIdx = embedRe.lastIndex;
      }
      if (lastIdx < line.length) {
        this.renderTextSegment(line.slice(lastIdx), container);
      }
    }
  }
  /** Render a text segment with inline #tag and [[wikilink]] support. */
  renderTextSegment(text, container) {
    const tagRe = new RegExp(INLINE_TAG_RE.source, INLINE_TAG_RE.flags);
    const linkRe = new RegExp(WIKILINK_RE.source, WIKILINK_RE.flags);
    const matches = [];
    let m;
    while ((m = tagRe.exec(text)) !== null) {
      matches.push({ index: m.index, length: m[0].length, type: "tag", tagName: m[1] });
    }
    while ((m = linkRe.exec(text)) !== null) {
      matches.push({ index: m.index, length: m[0].length, type: "link", linkPath: m[1], linkAlias: m[2] });
    }
    matches.sort((a, b) => a.index - b.index);
    let lastIndex = 0;
    for (const match of matches) {
      if (match.index < lastIndex)
        continue;
      if (match.index > lastIndex) {
        container.appendText(text.slice(lastIndex, match.index));
      }
      if (match.type === "tag" && match.tagName) {
        const tagSpan = container.createSpan({ cls: "memos-inline-tag", text: `#${match.tagName}` });
        tagSpan.dataset["tag"] = match.tagName;
        tagSpan.addEventListener("click", (e) => {
          e.stopPropagation();
          this.handleTagClick(match.tagName);
        });
      } else if (match.type === "link" && match.linkPath) {
        const displayText = match.linkAlias || match.linkPath;
        const linkSpan = container.createSpan({ cls: "memos-wikilink", text: displayText });
        linkSpan.dataset["href"] = match.linkPath;
        linkSpan.addEventListener("click", (e) => {
          e.stopPropagation();
          this.app.workspace.openLinkText(match.linkPath, "", false);
        });
        linkSpan.addEventListener("mouseover", (e) => {
          this.app.workspace.trigger("hover-link", {
            event: e,
            source: VIEW_TYPE_MEMOS,
            hoverParent: this,
            targetEl: linkSpan,
            linktext: match.linkPath,
            sourcePath: ""
          });
        });
      }
      lastIndex = match.index + match.length;
    }
    if (lastIndex < text.length) {
      container.appendText(text.slice(lastIndex));
    }
  }
  /** Render a ![[embed]] — show image if it's an image file, otherwise plain text. */
  renderEmbed(name, container) {
    var _a, _b;
    const ext = (_b = (_a = name.split(".").pop()) == null ? void 0 : _a.toLowerCase()) != null ? _b : "";
    if (!_MemosView.IMAGE_EXTENSIONS.includes(ext)) {
      container.appendText(`![[${name}]]`);
      return;
    }
    const file = this.app.metadataCache.getFirstLinkpathDest(name, "");
    if (!file) {
      container.appendText(`![[${name}]]`);
      return;
    }
    const resourcePath = this.app.vault.getResourcePath(file);
    const img = container.createEl("img", {
      cls: "memos-card-image",
      attr: {
        src: resourcePath,
        alt: name,
        loading: "lazy"
      }
    });
    img.addEventListener("click", (e) => {
      e.stopPropagation();
    });
  }
  handleTagClick(tag) {
    if (tag === null) {
      this.activeTag = null;
    } else {
      this.activeTag = this.activeTag === tag ? null : tag;
    }
    this.refresh();
  }
  /** Return memos filtered by the currently active tag and date filters. */
  getFilteredMemos() {
    let filtered = this.memos;
    if (this.activeTag) {
      filtered = filtered.filter((m) => m.tags.includes(this.activeTag));
    }
    if (this.activeDateFilter) {
      filtered = filtered.filter((m) => m.dateLabel === this.activeDateFilter);
    }
    return filtered;
  }
  handleRandomReview() {
    if (this.highlightedCardEl) {
      this.highlightedCardEl.removeClass("memos-card-highlighted");
      this.highlightedCardEl = null;
    }
    const filtered = this.getFilteredMemos();
    if (filtered.length === 0)
      return;
    const idx = Math.floor(Math.random() * filtered.length);
    const target = filtered[idx];
    const cardEl = this.contentEl.querySelector(
      `[data-path="${CSS.escape(target.file.path)}"]`
    );
    if (cardEl) {
      cardEl.addClass("memos-card-highlighted");
      this.highlightedCardEl = cardEl;
      cardEl.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  }
  handleDateFilter(date) {
    this.activeDateFilter = this.activeDateFilter === date ? null : date;
    this.refresh();
  }
  handleStatsToggle() {
    this.plugin.settings.statsCollapsed = !this.plugin.settings.statsCollapsed;
    this.plugin.saveSettings();
    this.refresh();
  }
  openMemo(file) {
    const existing = this.app.workspace.getLeavesOfType("markdown").find((leaf) => {
      const viewFile = leaf.view.file;
      return (viewFile == null ? void 0 : viewFile.path) === file.path;
    });
    if (existing) {
      this.app.workspace.revealLeaf(existing);
    } else {
      const leaf = this.app.workspace.getLeaf("tab");
      leaf.openFile(file);
    }
  }
};
var MemosView = _MemosView;
MemosView.IMAGE_EXTENSIONS = ["png", "jpg", "jpeg", "gif", "webp", "svg"];
MemosView.EMBED_RE = /!\[\[(.+?)\]\]/g;

// src/capture-view.ts
var import_obsidian5 = require("obsidian");
var IMAGE_EXTENSIONS = ["png", "jpg", "jpeg", "gif", "webp", "svg"];
var ImageSuggestModal = class extends import_obsidian5.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
    this.setPlaceholder("\u641C\u7D22\u56FE\u7247\u6587\u4EF6\u2026");
  }
  getItems() {
    return this.app.vault.getFiles().filter(
      (f) => IMAGE_EXTENSIONS.includes(f.extension.toLowerCase())
    );
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file) {
    this.onChoose(file);
  }
};
var NoteSuggestModal = class extends import_obsidian5.FuzzySuggestModal {
  constructor(app, onChoose, onDismiss) {
    super(app);
    this.onChoose = onChoose;
    this.onDismiss = onDismiss;
    this.setPlaceholder("\u641C\u7D22\u7B14\u8BB0\u2026");
  }
  getItems() {
    return this.app.vault.getMarkdownFiles();
  }
  getItemText(file) {
    return file.basename;
  }
  onChooseItem(file) {
    this.onChoose(file);
  }
  onClose() {
    setTimeout(() => {
      var _a;
      (_a = this.onDismiss) == null ? void 0 : _a.call(this);
    }, 50);
  }
};
var CaptureItemView = class extends import_obsidian5.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    /** Explicit tags added via the pill UI (without leading #). */
    this.tags = [];
    /** Selected mood (emoji string or empty). */
    this.selectedMood = "";
    /** Selected source (string or empty). */
    this.selectedSource = "";
    /** Prevents multiple wikilink modals from opening simultaneously. */
    this.wikilinkModalOpen = false;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CAPTURE;
  }
  getDisplayText() {
    return "Quick Capture";
  }
  getIcon() {
    return "pencil";
  }
  async onOpen() {
    const container = this.contentEl;
    container.empty();
    container.addClass("memos-capture-card-container");
    const closeBtn = container.createEl("button", {
      cls: "memos-capture-close clickable-icon",
      attr: { "aria-label": "\u8FD4\u56DE" }
    });
    (0, import_obsidian5.setIcon)(closeBtn, "arrow-left");
    closeBtn.addEventListener("click", async () => {
      await this.plugin.activateView();
      this.leaf.detach();
    });
    const card = container.createDiv("memos-capture-card");
    const textareaWrap = card.createDiv("memos-capture-card-textarea-wrap");
    this.textarea = textareaWrap.createEl("textarea", {
      cls: "memos-capture-card-textarea",
      attr: { placeholder: "What's on your mind?" }
    });
    this.textarea.addEventListener("input", () => {
      this.handleWikilinkTrigger();
    });
    this.tags = [];
    this.tagsContainer = card.createDiv("memos-capture-card-tags");
    this.renderTags();
    if (this.plugin.settings.enableMood) {
      const moodRow = card.createDiv("memos-capture-meta-row");
      moodRow.createSpan({ cls: "memos-capture-meta-label", text: "Mood" });
      const moodPills = moodRow.createDiv("memos-capture-meta-pills");
      for (const emoji of this.plugin.settings.moodOptions) {
        const pill = moodPills.createSpan({ cls: "memos-capture-meta-pill", text: emoji });
        pill.addEventListener("click", () => {
          this.selectedMood = this.selectedMood === emoji ? "" : emoji;
          moodPills.querySelectorAll(".memos-capture-meta-pill").forEach((el) => {
            el.removeClass("is-active");
          });
          if (this.selectedMood)
            pill.addClass("is-active");
        });
      }
    }
    if (this.plugin.settings.enableSource) {
      const sourceRow = card.createDiv("memos-capture-meta-row");
      sourceRow.createSpan({ cls: "memos-capture-meta-label", text: "Source" });
      const sourcePills = sourceRow.createDiv("memos-capture-meta-pills");
      for (const src of this.plugin.settings.sourceOptions) {
        const pill = sourcePills.createSpan({ cls: "memos-capture-meta-pill", text: src });
        pill.addEventListener("click", () => {
          this.selectedSource = this.selectedSource === src ? "" : src;
          sourcePills.querySelectorAll(".memos-capture-meta-pill").forEach((el) => {
            el.removeClass("is-active");
          });
          if (this.selectedSource)
            pill.addClass("is-active");
        });
      }
    }
    card.createDiv("memos-capture-card-divider");
    const footer = card.createDiv("memos-capture-card-footer");
    const footerLeft = footer.createDiv("memos-capture-card-footer-left");
    const footerRight = footer.createDiv("memos-capture-card-footer-right");
    const imageBtn = footerLeft.createEl("button", {
      cls: "memos-capture-card-foot-btn clickable-icon",
      attr: { "aria-label": "\u63D2\u5165\u56FE\u7247" }
    });
    (0, import_obsidian5.setIcon)(imageBtn, "image");
    imageBtn.addEventListener("click", () => {
      new ImageSuggestModal(this.app, (file) => {
        this.insertAtCursor(`![[${file.name}]]`);
      }).open();
    });
    const tagBtn = footerLeft.createEl("button", {
      cls: "memos-capture-card-foot-btn clickable-icon",
      attr: { "aria-label": "\u6DFB\u52A0\u6807\u7B7E" }
    });
    (0, import_obsidian5.setIcon)(tagBtn, "hash");
    tagBtn.addEventListener("click", () => {
      this.showTagInput();
    });
    if (this.plugin.settings.useFixedTag && this.plugin.settings.fixedTag) {
      footerLeft.createSpan({
        cls: "memos-capture-card-hint",
        text: `\u56FA\u5B9A\u6807\u7B7E: #${this.plugin.settings.fixedTag.replace(/^#+/, "")}`
      });
    }
    const saveBtn = footerRight.createEl("button", {
      cls: "memos-capture-card-save",
      text: "\u4FDD\u5B58 Memo"
    });
    saveBtn.addEventListener("click", () => {
      this.handleSave();
    });
    container.addEventListener("keydown", (e) => {
      if ((e.ctrlKey || e.metaKey) && e.key === "Enter") {
        e.preventDefault();
        this.handleSave();
      }
    });
    setTimeout(() => this.textarea.focus(), 100);
  }
  async onClose() {
    this.contentEl.empty();
  }
  // ── Tag pill UI ──────────────────────────────────────────
  /** Re-render the tags container: existing pills + the add button. */
  renderTags() {
    this.tagsContainer.empty();
    for (const tag of this.tags) {
      const pill = this.tagsContainer.createDiv("memos-capture-card-tag");
      pill.createSpan({ text: `#${tag}` });
      const removeBtn = pill.createSpan({
        cls: "memos-capture-card-tag-remove",
        text: "\xD7"
      });
      removeBtn.addEventListener("click", () => {
        this.tags = this.tags.filter((t) => t !== tag);
        this.renderTags();
      });
    }
    const addBtn = this.tagsContainer.createDiv("memos-capture-card-tag-add");
    addBtn.setText("+ \u6DFB\u52A0\u6807\u7B7E");
    addBtn.addEventListener("click", () => {
      this.showTagInput(addBtn);
    });
  }
  /** Replace the add-button with an inline input for entering a new tag. */
  showTagInput(replaceEl) {
    const target = replaceEl != null ? replaceEl : this.tagsContainer.querySelector(
      ".memos-capture-card-tag-add"
    );
    if (!target)
      return;
    const input = document.createElement("input");
    input.type = "text";
    input.className = "memos-capture-card-tag-input";
    input.placeholder = "\u6807\u7B7E\u540D\u2026";
    target.replaceWith(input);
    input.focus();
    let composing = false;
    input.addEventListener("compositionstart", () => {
      composing = true;
    });
    input.addEventListener("compositionend", () => {
      composing = false;
    });
    const commit = () => {
      const values = parseTags(input.value);
      for (const v of values) {
        if (!this.tags.includes(v)) {
          this.tags.push(v);
        }
      }
      this.renderTags();
    };
    input.addEventListener("keydown", (e) => {
      if (composing)
        return;
      if (e.key === "Enter" || e.key === " " || e.key === ",") {
        e.preventDefault();
        commit();
      }
      if (e.key === "Escape") {
        e.preventDefault();
        this.renderTags();
      }
    });
    input.addEventListener("blur", () => {
      commit();
    });
  }
  // ── Helpers ──────────────────────────────────────────────
  /**
   * Detect "[[" typed in the textarea and open note suggest modal.
   * On selection: replaces the "[[" with "[[NoteName]]".
   * On dismiss: leaves the "[[" as-is so the user can type manually.
   */
  handleWikilinkTrigger() {
    if (this.wikilinkModalOpen)
      return;
    const ta = this.textarea;
    const cursor = ta.selectionStart;
    const textBefore = ta.value.slice(0, cursor);
    if (!textBefore.endsWith("[["))
      return;
    this.wikilinkModalOpen = true;
    const bracketStart = cursor - 2;
    let chosen = false;
    new NoteSuggestModal(
      this.app,
      (file) => {
        chosen = true;
        const linkText = `[[${file.basename}]]`;
        const before = ta.value.slice(0, bracketStart);
        const after = ta.value.slice(cursor);
        ta.value = before + linkText + after;
        const newPos = bracketStart + linkText.length;
        ta.selectionStart = newPos;
        ta.selectionEnd = newPos;
        ta.focus();
        this.wikilinkModalOpen = false;
      },
      () => {
        if (!chosen) {
          ta.focus();
          this.wikilinkModalOpen = false;
        }
      }
    ).open();
  }
  /** Insert text at the current cursor position in the textarea. */
  insertAtCursor(text) {
    const ta = this.textarea;
    const start = ta.selectionStart;
    const end = ta.selectionEnd;
    const before = ta.value.slice(0, start);
    const after = ta.value.slice(end);
    ta.value = before + text + after;
    const newPos = start + text.length;
    ta.selectionStart = newPos;
    ta.selectionEnd = newPos;
    ta.focus();
  }
  async handleSave() {
    const trimmed = this.textarea.value.trim();
    if (!trimmed) {
      new import_obsidian5.Notice("Memo cannot be empty.");
      return;
    }
    const explicitTags = [...this.tags];
    const inlineTags = extractInlineTags(trimmed);
    const allTags = Array.from(/* @__PURE__ */ new Set([...explicitTags, ...inlineTags]));
    const meta = {};
    if (this.selectedMood)
      meta.mood = this.selectedMood;
    if (this.selectedSource)
      meta.source = this.selectedSource;
    try {
      await this.plugin.saveMemo(trimmed, allTags, Object.keys(meta).length > 0 ? meta : void 0);
      new import_obsidian5.Notice("Memo saved!");
      await this.plugin.activateView();
      this.leaf.detach();
    } catch (err) {
      new import_obsidian5.Notice(
        `Failed to save memo: ${err instanceof Error ? err.message : String(err)}`
      );
    }
  }
};

// src/settings.ts
var import_obsidian6 = require("obsidian");
var MemosSettingTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian6.Setting(containerEl).setName("Memos Settings").setHeading();
    new import_obsidian6.Setting(containerEl).setName("Save folder").setDesc("Folder where new memos are saved (relative to vault root).").addText(
      (text) => text.setPlaceholder("00-Inbox").setValue(this.plugin.settings.saveFolder).onChange(async (value) => {
        this.plugin.settings.saveFolder = value.trim() || "00-Inbox";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Use fixed tag").setDesc("Automatically add a tag to every memo you capture.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.useFixedTag).onChange(async (value) => {
        this.plugin.settings.useFixedTag = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.useFixedTag) {
      new import_obsidian6.Setting(containerEl).setName("Fixed tag value").setDesc("This tag will be added to every memo (without #).").addText(
        (text) => text.setPlaceholder("memo").setValue(this.plugin.settings.fixedTag).onChange(async (value) => {
          this.plugin.settings.fixedTag = value.trim().replace(/^#+/, "");
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian6.Setting(containerEl).setName("Quick capture entry note").setDesc(
      `Path to the entry note that triggers the capture modal when opened. Use with the iOS widget's "Open a specific note" feature.`
    ).addText(
      (text) => text.setPlaceholder("Quick Capture.md").setValue(this.plugin.settings.captureNotePath).onChange(async (value) => {
        this.plugin.settings.captureNotePath = value.trim() || "Quick Capture.md";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Extended metadata").setHeading();
    new import_obsidian6.Setting(containerEl).setName("Enable mood").setDesc("Show mood picker when capturing memos. Adds a mood field to frontmatter for Dataview queries.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableMood).onChange(async (value) => {
        this.plugin.settings.enableMood = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.enableMood) {
      new import_obsidian6.Setting(containerEl).setName("Mood options").setDesc("Comma-separated emojis for the mood picker.").addText(
        (text) => text.setPlaceholder("\u{1F4A1}, \u{1F914}, \u{1F60A}, \u{1F624}, \u{1F4D6}").setValue(this.plugin.settings.moodOptions.join(", ")).onChange(async (value) => {
          this.plugin.settings.moodOptions = value.split(",").map((s) => s.trim()).filter(Boolean);
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian6.Setting(containerEl).setName("Enable source").setDesc("Show source picker when capturing memos. Adds a source field to frontmatter for Dataview queries.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableSource).onChange(async (value) => {
        this.plugin.settings.enableSource = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.enableSource) {
      new import_obsidian6.Setting(containerEl).setName("Source options").setDesc("Comma-separated source labels (e.g. thought, kindle, web).").addText(
        (text) => text.setPlaceholder("thought, kindle, web, conversation, podcast").setValue(this.plugin.settings.sourceOptions.join(", ")).onChange(async (value) => {
          this.plugin.settings.sourceOptions = value.split(",").map((s) => s.trim()).filter(Boolean);
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian6.Setting(containerEl).setName("Image export").setHeading();
    new import_obsidian6.Setting(containerEl).setName("Show author name").setDesc("Display your name at the bottom of exported memo images.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showAuthorInExport).onChange(async (value) => {
        this.plugin.settings.showAuthorInExport = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.showAuthorInExport) {
      new import_obsidian6.Setting(containerEl).setName("Author name").setDesc("Your name or brand to show on exported images.").addText(
        (text) => text.setPlaceholder("Your name").setValue(this.plugin.settings.authorName).onChange(async (value) => {
          this.plugin.settings.authorName = value.trim();
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian6.Setting(containerEl).setName("Show branding").setDesc('Display "Quick Memos for Obsidian" at the bottom of exported images.').addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showBrandingInExport).onChange(async (value) => {
        this.plugin.settings.showBrandingInExport = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/plugin.ts
var MemosPlugin = class extends import_obsidian7.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_MEMOS, (leaf) => new MemosView(leaf, this));
    this.registerView(VIEW_TYPE_CAPTURE, (leaf) => new CaptureItemView(leaf, this));
    this.addRibbonIcon("sticky-note", "Open Memos view", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-memos-capture",
      name: "Quick capture",
      callback: () => {
        this.activateCaptureView();
      }
    });
    this.addCommand({
      id: "open-memos-view",
      name: "Open Memos view",
      callback: () => {
        this.activateView();
      }
    });
    this.addCommand({
      id: "create-capture-note",
      name: "Create quick capture entry note",
      callback: async () => {
        const path = this.settings.captureNotePath;
        if (this.app.vault.getAbstractFileByPath(path)) {
          new import_obsidian7.Notice(`Entry note already exists: ${path}`);
          return;
        }
        const content = [
          "This note is used by the Memos plugin as a quick capture entry point.",
          "",
          "**How to use on iOS:**",
          "1. Long-press the Obsidian home screen widget",
          "2. Tap Edit Widget",
          '3. Set "Open a specific note" to this note',
          "4. Tapping the widget will open Obsidian and automatically show the capture dialog",
          "",
          "> Do not delete this note if you want the widget shortcut to work."
        ].join("\n");
        await this.app.vault.create(path, content);
        new import_obsidian7.Notice(`Created entry note: ${path}`);
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        if (file && file.path === (0, import_obsidian7.normalizePath)(this.settings.captureNotePath)) {
          this.activateCaptureView();
        }
      })
    );
    this.addSettingTab(new MemosSettingTab(this.app, this));
    this.registerObsidianProtocolHandler("memo", async (params) => {
      const content = (params.content || params.text || "").trim();
      const tags = (params.tags || "").split(",").map((t) => t.trim()).filter(Boolean);
      const mood = (params.mood || "").trim();
      const source = (params.source || "").trim();
      if (!content) {
        new import_obsidian7.Notice("Memo content is empty.");
        return;
      }
      const meta = {};
      if (mood)
        meta.mood = mood;
      if (source)
        meta.source = source;
      await this.saveMemo(content, tags, Object.keys(meta).length > 0 ? meta : void 0);
      new import_obsidian7.Notice("Memo saved!");
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        const selection = editor.getSelection();
        if (!selection)
          return;
        menu.addItem((item) => {
          item.setTitle("Save as Memo").setIcon("sticky-note").onClick(async () => {
            const tags = extractInlineTags(selection);
            await this.saveMemo(selection, tags);
            new import_obsidian7.Notice("Selection saved as Memo!");
          });
        });
      })
    );
    this.registerMarkdownPostProcessor((el) => {
      const embeds = el.querySelectorAll('.internal-embed:not([class*="memos-transclusion"])');
      this.tagMemoEmbeds(embeds);
      const observer = new MutationObserver((mutations) => {
        var _a, _b, _c;
        for (const mutation of mutations) {
          for (const node of mutation.addedNodes) {
            if (node instanceof HTMLElement) {
              const added = ((_a = node.matches) == null ? void 0 : _a.call(node, ".internal-embed")) ? [node] : Array.from((_c = (_b = node.querySelectorAll) == null ? void 0 : _b.call(node, ".internal-embed")) != null ? _c : []);
              if (added.length > 0)
                this.tagMemoEmbeds(added);
            }
          }
        }
      });
      observer.observe(el, { childList: true, subtree: true });
      setTimeout(() => observer.disconnect(), 5e3);
    });
    this.app.workspace.onLayoutReady(() => {
      if (import_obsidian7.Platform.isMobile) {
        this.activateView();
      }
    });
  }
  onunload() {
  }
  async activateCaptureView() {
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.setViewState({ type: VIEW_TYPE_CAPTURE, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_MEMOS);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.setViewState({ type: VIEW_TYPE_MEMOS, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
  async saveMemo(content, tags, meta) {
    const now = /* @__PURE__ */ new Date();
    const iso = now.toISOString();
    const pad = (n, len = 2) => n.toString().padStart(len, "0");
    const dateStr = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`;
    const timeStr = `${pad(now.getHours())}-${pad(now.getMinutes())}-${pad(now.getSeconds())}`;
    const ms = pad(now.getMilliseconds(), 3);
    const filename = `memo-${dateStr}-${timeStr}-${ms}.md`;
    const allTags = [];
    if (this.settings.useFixedTag && this.settings.fixedTag) {
      allTags.push(this.settings.fixedTag.replace(/^#+/, ""));
    }
    for (const t of tags) {
      const clean = t.replace(/^#+/, "");
      if (clean && !allTags.includes(clean)) {
        allTags.push(clean);
      }
    }
    const tagYaml = allTags.length > 0 ? `tags:
${allTags.map((t) => `  - ${t}`).join("\n")}` : "tags: []";
    let extraYaml = "";
    if (meta == null ? void 0 : meta.mood)
      extraYaml += `mood: "${meta.mood}"
`;
    if (meta == null ? void 0 : meta.source)
      extraYaml += `source: "${meta.source}"
`;
    extraYaml += "status: active\n";
    const frontmatter = `---
created: ${iso}
type: memo
${tagYaml}
${extraYaml}---

`;
    const fileContent = frontmatter + content;
    const folder = (0, import_obsidian7.normalizePath)(this.settings.saveFolder);
    if (!this.app.vault.getAbstractFileByPath(folder)) {
      await this.app.vault.createFolder(folder);
    }
    const filePath = (0, import_obsidian7.normalizePath)(`${folder}/${filename}`);
    await this.app.vault.create(filePath, fileContent);
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_MEMOS)) {
      const view = leaf.view;
      if (view instanceof MemosView) {
        await view.refresh();
      }
    }
    return filename;
  }
  /** Tag embed elements whose source file has type: memo in frontmatter. */
  tagMemoEmbeds(embeds) {
    for (const embed of embeds) {
      if (embed.hasClass("memos-transclusion-card"))
        continue;
      const src = embed.getAttribute("src");
      if (!src)
        continue;
      const file = this.app.metadataCache.getFirstLinkpathDest(src, "");
      if (!file)
        continue;
      const cache = this.app.metadataCache.getFileCache(file);
      if (!(cache == null ? void 0 : cache.frontmatter) || cache.frontmatter["type"] !== "memo")
        continue;
      embed.addClass("memos-transclusion-card");
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
